name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm test
  trigger-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - verify
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: >-
            POST
            /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: travi
          repo: ioc
          ref: ${{ github.ref }}
          workflow_id: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
