name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm test
  trigger-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - verify
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: >-
            POST
            /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: travi
          repo: ioc
          ref: ${{ github.ref }}
          workflow_id: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
